import type { InstagramGalleryPost } from './instagram-gallery';

export const instagramGalleryPosts = [
  {
    id: 'DYFg0Q3tdfn',
    title: 'Kemn Ljemr - Concert reel',
    url: 'https://www.instagram.com/bermel_fest/reel/DYFg0Q3tdfn/',
    event: 'kemn-ljemr',
    credit: 'bermel_fest',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DYFg0Q3tdfn/01.mp4',
        poster: '/media/instagram/DYFg0Q3tdfn/01-poster.webp',
        width: 960,
        height: 720,
        alt: 'Lij Mic performing at Bermel Fest × Kemn Ljemr',
      },
    ],
  },
  {
    id: 'DX4Aty8DMJe',
    title: 'Kemn Ljemr - Live concert album',
    url: 'https://www.instagram.com/lij_mic_faf/p/DX4Aty8DMJe/',
    event: 'kemn-ljemr',
    credit: 'lij_mic_faf',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/01.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic concert crowd and stage at Bermel Fest × Kemn Ljemr',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/02.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/02-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic beneath stage flames at Bermel Fest × Kemn Ljemr',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/03.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/03-poster.webp',
        width: 720,
        height: 720,
        alt: 'Wide view of the Bermel Fest × Kemn Ljemr concert stage',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/04.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/04-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic on the concert stage with flame effects',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/05.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/05-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic performing between stage flame towers',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/06.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/06-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic suspended above the Bermel Fest × Kemn Ljemr stage',
      },
      {
        type: 'video',
        src: '/media/instagram/DX4Aty8DMJe/07.mp4',
        poster: '/media/instagram/DX4Aty8DMJe/07-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic and the band performing on the concert stage',
      },
    ],
  },
  {
    id: 'DT0aR7FjN3s',
    url: 'https://www.instagram.com/shega_events/p/DT0aR7FjN3s/',
    event: 'hello-hawassa',
    credit: 'shega_events',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DT0aR7FjN3s/01.webp',
        width: 1440,
        height: 1440,
        alt: 'Hello Hawassa concert poster featuring Yohana',
      },
    ],
  },
  {
    id: 'DQFAENfjbO7',
    url: 'https://www.instagram.com/bermel_fest/reel/DQFAENfjbO7/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DQFAENfjbO7/01.mp4',
        poster: '/media/instagram/DQFAENfjbO7/01-poster.webp',
        width: 480,
        height: 360,
        alt: 'Crowd reactions at the 19th edition of Bermel Fest',
      },
    ],
  },
  {
    id: 'DOGjctODR4G',
    url: 'https://www.instagram.com/bermel_fest/p/DOGjctODR4G/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/01.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 1 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/02.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 2 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/03.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 3 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/04.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 4 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/05.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 5 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/06.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 6 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/07.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 7 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/08.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 8 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/09.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 9 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/10.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 10 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/11.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 11 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/12.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 12 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/13.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 13 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/14.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 14 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/15.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 15 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/16.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 16 from the 19th edition album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGjctODR4G/17.webp',
        width: 1440,
        height: 1795,
        alt: 'Bermel Fest, photo 17 from the 19th edition album',
      },
    ],
  },
  {
    id: 'DZIF0nbDdTP',
    url: 'https://www.instagram.com/p/DZIF0nbDdTP/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/01.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/02.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/03.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/04.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 4 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/05.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 5 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/06.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 6 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/07.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 7 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/08.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 8 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/09.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 9 from the event album',
      },
    ],
  },
  {
    id: 'DYpWL3hjfTF',
    url: 'https://www.instagram.com/p/DYpWL3hjfTF/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/01.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/02.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/03.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
    ],
  },
  {
    id: 'DOGw94yguXX',
    url: 'https://www.instagram.com/p/DOGw94yguXX/',
    event: 'bermel',
    credit: 'jebastudio_',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/01.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/02.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/03.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/04.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 4 from the event album',
      },
    ],
  },
  {
    id: 'DWtn0mvEaBb',
    title: 'Kemn Ljemr - Artist announcements',
    url: 'https://www.instagram.com/reel/DWtn0mvEaBb/',
    event: 'kemn-ljemr',
    credit: 'lij_mic_faf',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DWtn0mvEaBb/01.mp4',
        poster: '/media/instagram/DWtn0mvEaBb/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Lij Mic announcement for the Kemn Ljemr album release',
        source: {
          url: 'https://www.instagram.com/reel/DWtn0mvEaBb/',
          credit: 'lij_mic_faf',
        },
      },
      {
        type: 'video',
        src: '/media/instagram/DW--91rjIAV/01.mp4',
        poster: '/media/instagram/DW--91rjIAV/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Melat announcement for the Kemn Ljemr album release',
        source: {
          url: 'https://www.instagram.com/p/DW--91rjIAV/',
          credit: 'shega_events',
        },
      },
      {
        type: 'video',
        src: '/media/instagram/DW_WyoaDEZu/01.mp4',
        poster: '/media/instagram/DW_WyoaDEZu/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Addis Mulat announcement for the Kemn Ljemr album release',
        source: {
          url: 'https://www.instagram.com/p/DW_WyoaDEZu/',
          credit: 'shega_events',
        },
      },
      {
        type: 'video',
        src: '/media/instagram/DW_3Fy9jCyE/01.mp4',
        poster: '/media/instagram/DW_3Fy9jCyE/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Betty G announcement for the Kemn Ljemr album release',
        source: {
          url: 'https://www.instagram.com/p/DW_3Fy9jCyE/',
          credit: 'shega_events',
        },
      },
      {
        type: 'image',
        src: '/media/instagram/DW--91rjIAV/02.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr album-release poster featuring Lij Mic',
        source: {
          url: 'https://www.instagram.com/p/DW--91rjIAV/',
          credit: 'shega_events',
        },
      },
      {
        type: 'image',
        src: '/media/instagram/DW--91rjIAV/03.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr album-release ticket information',
        source: {
          url: 'https://www.instagram.com/p/DW--91rjIAV/',
          credit: 'shega_events',
        },
      },
    ],
  },
  {
    id: 'DUoBDUXjOES',
    url: 'https://www.instagram.com/p/DUoBDUXjOES/',
    event: 'hello-hawassa',
    credit: 'shega_events',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DUoBDUXjOES/01.webp',
        width: 1440,
        height: 1440,
        alt: 'Hello Hawassa, photo 1 from the event album',
      },
    ],
  },
  {
    id: 'DUqm7eOjJaa',
    url: 'https://www.instagram.com/reel/DUqm7eOjJaa/',
    event: 'hello-hawassa',
    credit: 'shega_events',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DUqm7eOjJaa/01.mp4',
        poster: '/media/instagram/DUqm7eOjJaa/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Hello Hawassa, event reel',
      },
    ],
  },
  {
    id: 'DU0B-9iCkC-',
    url: 'https://www.instagram.com/reel/DU0B-9iCkC-/',
    event: 'hello-hawassa',
    credit: 'thexxiet',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DU0B-9iCkC-/01.mp4',
        poster: '/media/instagram/DU0B-9iCkC-/01-poster.webp',
        width: 720,
        height: 1280,
        alt: 'Hello Hawassa, event reel',
      },
    ],
  },
] satisfies readonly InstagramGalleryPost[];
