import type { InstagramGalleryPost } from './instagram-gallery';

export const instagramGalleryPosts = [
  {
    id: 'DZIF0nbDdTP',
    url: 'https://www.instagram.com/p/DZIF0nbDdTP/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/01.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/02.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/03.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/04.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 4 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/05.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 5 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/06.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 6 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/07.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 7 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/08.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 8 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DZIF0nbDdTP/09.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 9 from the event album',
      },
    ],
  },
  {
    id: 'DYpWL3hjfTF',
    url: 'https://www.instagram.com/p/DYpWL3hjfTF/',
    event: 'bermel',
    credit: 'bermel_fest',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/01.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/02.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DYpWL3hjfTF/03.webp',
        width: 1440,
        height: 960,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
    ],
  },
  {
    id: 'DOGw94yguXX',
    url: 'https://www.instagram.com/p/DOGw94yguXX/',
    event: 'bermel',
    credit: 'jebastudio_',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/01.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 1 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/02.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/03.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 3 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DOGw94yguXX/04.webp',
        width: 1080,
        height: 1440,
        alt: 'Bermel Fest, photo 4 from the event album',
      },
    ],
  },
  {
    id: 'DWtn0mvEaBb',
    url: 'https://www.instagram.com/reel/DWtn0mvEaBb/',
    event: 'kemn-ljemr',
    credit: 'lij_mic_faf',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DWtn0mvEaBb/01.mp4',
        poster: '/media/instagram/DWtn0mvEaBb/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Kemn Ljemr, event reel',
      },
    ],
  },
  {
    id: 'DW--91rjIAV',
    url: 'https://www.instagram.com/p/DW--91rjIAV/',
    event: 'kemn-ljemr',
    credit: 'shega_events',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DW--91rjIAV/01.mp4',
        poster: '/media/instagram/DW--91rjIAV/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Kemn Ljemr, event reel 1',
      },
      {
        type: 'image',
        src: '/media/instagram/DW--91rjIAV/02.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DW--91rjIAV/03.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 3 from the event album',
      },
    ],
  },
  {
    id: 'DW_WyoaDEZu',
    url: 'https://www.instagram.com/p/DW_WyoaDEZu/',
    event: 'kemn-ljemr',
    credit: 'shega_events',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DW_WyoaDEZu/01.mp4',
        poster: '/media/instagram/DW_WyoaDEZu/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Kemn Ljemr, event reel 1',
      },
      {
        type: 'image',
        src: '/media/instagram/DW_WyoaDEZu/02.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DW_WyoaDEZu/03.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 3 from the event album',
      },
    ],
  },
  {
    id: 'DW_3Fy9jCyE',
    url: 'https://www.instagram.com/p/DW_3Fy9jCyE/',
    event: 'kemn-ljemr',
    credit: 'shega_events',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DW_3Fy9jCyE/01.mp4',
        poster: '/media/instagram/DW_3Fy9jCyE/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Kemn Ljemr, event reel 1',
      },
      {
        type: 'image',
        src: '/media/instagram/DW_3Fy9jCyE/02.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 2 from the event album',
      },
      {
        type: 'image',
        src: '/media/instagram/DW_3Fy9jCyE/03.webp',
        width: 1440,
        height: 1440,
        alt: 'Kemn Ljemr, photo 3 from the event album',
      },
    ],
  },
  {
    id: 'DUoBDUXjOES',
    url: 'https://www.instagram.com/p/DUoBDUXjOES/',
    event: 'hello-hawassa',
    credit: 'shega_events',
    media: [
      {
        type: 'image',
        src: '/media/instagram/DUoBDUXjOES/01.webp',
        width: 1440,
        height: 1440,
        alt: 'Hello Hawassa, photo 1 from the event album',
      },
    ],
  },
  {
    id: 'DUqm7eOjJaa',
    url: 'https://www.instagram.com/reel/DUqm7eOjJaa/',
    event: 'hello-hawassa',
    credit: 'shega_events',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DUqm7eOjJaa/01.mp4',
        poster: '/media/instagram/DUqm7eOjJaa/01-poster.webp',
        width: 720,
        height: 720,
        alt: 'Hello Hawassa, event reel',
      },
    ],
  },
  {
    id: 'DU0B-9iCkC-',
    url: 'https://www.instagram.com/reel/DU0B-9iCkC-/',
    event: 'hello-hawassa',
    credit: 'thexxiet',
    media: [
      {
        type: 'video',
        src: '/media/instagram/DU0B-9iCkC-/01.mp4',
        poster: '/media/instagram/DU0B-9iCkC-/01-poster.webp',
        width: 720,
        height: 1280,
        alt: 'Hello Hawassa, event reel',
      },
    ],
  },
] satisfies readonly InstagramGalleryPost[];
